version: '3.9'

services:
  base-db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  test-db:
    image: postgres
    restart: always
    env_file:
      - test_db.env
    ports:
      - "6000:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  referral-system-api:
    build:
      dockerfile: Dockerfile
    image: referral-system-api:latest
    restart: always
    container_name: referral-system-api-dev
    depends_on:
      - base-db
    ports:
      - "8080:8000"
    volumes:
      - .:/referral-system-api
    networks:
      - backend

volumes:
  postgres_data:
  test_postgres_data:

networks:
  backend:
    driver: bridge